<?php

namespace app\admin\model;

use think\Model;

class Question extends Model
{
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Question::event('before_write',function($question){
            $question->node_id=
        });
    }


    /**
     * 获取所有数据
     * @param $limit
     * @param $rows
     * @param $where
     * @return array
     * @auther guozhen
     */
    public function getAll($limit, $rows, $where)
    {
        $count = $this->where($where)->count();
        $data = $this->limit($limit, $rows)->where($where)->field('id,question,create_time')->order('id','desc')->select();
        return [
            "total" => $count,
            "rows" => $data
        ];

    }
}
