<?php

namespace app\common\model;

use think\Model;

class HtmlTemplate extends Model
{
    /**
     * 初始化函数
     * @author guozhen
     */
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        HtmlTemplate::event("before_write", function ($template) {
            if (!empty($template->path)) {
                $zip=new \ZipArchive();
                $root=dirname(THINK_PATH);
                if($zip->open($root."/public/".$template->path)==true){
                    $zip->extractTo($root.'/public/upload/unHtmlTemplate');
                    $zip->close();
                }
            }
        });
    }

}
